### ISSUE TITLE
Standby mode not updated

### ISSUE THREAD

**Issue by garyak** [rfverbruggen/rachiopy#11]
Setting standby mode to On/Off from Lovelace UI is not reflected in Rachio App for iOS.  Also, the pop-up window for Standby mode switch does not follow the card.

**Comment by rfverbruggen** [comment]
Hi @garyak 

This sounds like a Home-assistant issue, or is this library related?

If this is Home-assistant related I would advise you to create a Home-assistant issue.
Otherwise please give some more information/screenshots/errors of what is going wrong so I can fix it.

Kind regards,

Robbert Verbruggen

**Comment by rfverbruggen** [comment]
Hi @garyak,

I'll close this issue for now.

Please feel free to open a new issue if you encounter an error regarding the API Wrapper.

Kind regards,

Robbert
