### ISSUE TITLE
unpredictable behavior

### ISSUE THREAD

**Issue by munnecke** [rfverbruggen/rachiopy#2]
When I write
`r.zone.start('2a17314c-30c3-4cae-a6f5-ec79f36d3109',5)`
I sometimes get a long delay (30 sec or so), and it returns `''`
other times, I get an `unhashable type` error.   It's not predictable which result I will get.

**Comment by rfverbruggen** [comment]
Thanks for your report, I'll post a solution soon!

**Comment by rfverbruggen** [comment]
At the moment the only thing I discovered is that when you start a zone nothing is returned. Is your zone starting when you execute this? 

Maybe I should send the response and content back with every request so that we can see what the http response message is.

https://rachio.readme.io/docs/publiczoneid

**Comment by rfverbruggen** [comment]
Think I fixed this issue in the newest version:

https://github.com/rfverbruggen/rachiopy/commit/f3baf0fe8767b3c28ffcaed2395055a839b691fb

Can you test and report it back to me, because if this is the sollution I have to edit the other put requests to.

**Comment by rfverbruggen** [comment]
Think I fixed this issue in the newest version:

https://github.com/rfverbruggen/rachiopy
